name: Deploy Yii2 Shop

on:
  push:
    branches: [ main ]

env:
  DOCKER_IMAGE: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/yii2-shop:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Pull the latest image
            docker pull ${{ secrets.DOCKER_USERNAME }}/yii2-shop:latest
            
            # Update the service
            docker service update --image ${{ secrets.DOCKER_USERNAME }}/yii2-shop:latest yii2-shop_app
            
            # Check service status
            docker service ps yii2-shop_app

      - name: Health Check
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Wait for service to be healthy
            for i in {1..10}; do
              if curl -f http://localhost/health; then
                echo "Service is healthy"
                exit 0
              fi
              sleep 10
            done
            echo "Service health check failed"
            exit 1 